/* ifstmt
 Parses strings in the language generated by the rule:
 <ifstmt> -> if (<boolexpr>) <statement>
 [else <statement>]
 */
void ifstmt();
void whilestmt();
void logical_math_expression();

int main(void){
    return 0;
}
void ifstmt(void) {
    if (nextToken != IF_CODE) 
    error();
    else {                
        lex();
        if (nextToken != LEFT_PAREN) 
        error();
        else {
            lex();
            boolexpr();
            if (nextToken != RIGHT_PAREN)  
            error();
            else {
                lex();
                statement();
                if (nextToken == ELSE_CODE) {
                    lex();
                    statement();
                    }
            
            }
        }
    }
}

void whilestmt(void){
    if(nextToken != WHILE_CODE)
    error();
    else {
        lex();
        if(nextToken != LEFT_PAREN)
        error();
        else{
            lex();
            boolexpr();
            if(nextToken != RIGHT_PAREN)
            error();
            else {
                lex();
                statement();
            }
        }
    }
}

void logical_math_expression(void){
    if(nextToken != FLOAT  nextToken != INT  nextToken != DOUBLE)
    error();
    else{
        lex();
        if(nextToken != IDENT)
        error();
        else{
            lex();
            if(nextToken != ASSIGN_OP)
            error();
            else{
                lex();
                if(nextToken != EMPTY_FUNC)
                statement(); 
                else{
                    lex();
                }
            }
        }
    }
}


        